# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('d_addr', models.BinaryField()),
                ('s_addr', models.BinaryField()),
                ('d_port', models.IntegerField()),
                ('s_port', models.IntegerField()),
                ('ip_prot', models.IntegerField()),
                ('iso_code', models.CharField(max_length=16)),
            ],
        ),
    ]
