# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_vis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='time',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
