# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_vis', '0002_auto_20170627_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='d_addr',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='packet',
            name='s_addr',
            field=models.CharField(max_length=64),
        ),
    ]
