# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet_vis', '0002_auto_20170710_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='time',
            field=models.FloatField(),
        ),
    ]
